---

- name: Clear wrong DHCP lease
  shell: |
    source /opt/vyatta/etc/functions/script-template
    run show dhcp server leases | grep {{ device_network["mac"] | lower }} | while read line; do ip=$(echo $line | awk '{print $1}')
        if [ "$ip" != "{{ device_network["address"] }}" ]; then
            echo "Clearing lease for {{ device_network["address"] }}"
            clear dhcp-server lease $ip
        else
            echo "No lease to clear for {{ device_network["address"] }}"
        fi
    done
  register: expectresult
  args:
    executable: /bin/vbash
  vars:
    ansible_connection: ssh
    ansible_host: "{{ hostvars[vyos_router]['prop_ipaddress'] }}"
    ansible_python_interpreter: "/usr/bin/python3"
  become: false
