---

- name: Register DNS
  shell: |
    # curl --location --request POST 'https://10.20.10.1/retrieve' --form data='{"op": "showConfig", "path": []}' --form key='{{ prop_admin_password }}'
    # curl --location --request POST 'https://{{ prop_router }}/retrieve' --form data='{"op": "showConfig", "path": []}' --form key='{{ prop_admin_password }}'
    {% if prop_vm_network is defined %}
      {% for vm_network in prop_vm_network %}
        {% if vm_network["dns"] is defined %}
          {% for dns in vm_network["dns"] %}
            # path='["service", "dns", "forwarding", "authoritative-domain", "{{ dns["domain"] }}", "records", "{{ dns["type"] | default("a") }}", "{{ dns["name"] | default(prop_hostname) }}", "address", "{{ vm_network["address"] }}"]'
            curl --location --request POST "https://{{ prop_router }}/configure" \
              --form 'data={"op": "set", "path": ["service", "dns", "forwarding", "authoritative-domain", "{{ dns["domain"] }}", "records", "{{ dns["type"] | default("a") }}", "{{ dns["name"] | default(prop_hostname) }}", "address", "{{ vm_network["address"] }}"]}' \
              --form key="{{ prop_admin_password }}"
          {% endfor %}
        {% endif %}
      {% endfor %}
    {% endif %}
  args:
    executable: /bin/bash
  connection: local
  become: true

- name: Register DHCP
  shell: |
    {% if prop_vm_network is defined %}
      {% for vm_network in prop_vm_network %}
        {% if vm_network["vlan"] is defined %}
          {% if vm_network["subnet"] is defined %}
            curl --location --request POST 'https://{{ prop_router }}/configure' \
              --form 'data=[{"op": "set", "path": ["service", "dhcp-server", "shared-network-name", "{{ vm_network["vlan"] }}", "subnet", "{{ vm_network["subnet"] }}", "static-mapping", "{{ prop_hostname }}", "description", "{{ prop_description | default("[undefined]") }}"]}, 
                            {"op": "set", "path": ["service", "dhcp-server", "shared-network-name", "{{ vm_network["vlan"] }}", "subnet", "{{ vm_network["subnet"] }}", "static-mapping", "{{ prop_hostname }}", "ip-address", "{{ vm_network["address"] }}"]}, 
                            {"op": "set", "path": ["service", "dhcp-server", "shared-network-name", "{{ vm_network["vlan"] }}", "subnet", "{{ vm_network["subnet"] }}", "static-mapping", "{{ prop_hostname }}", "mac", "{{ vm_network["mac"] }}"]}]' \
              --form key="{{ prop_admin_password }}"
          {% endif %}
        {% endif %}
      {% endfor %}
    {% endif %}
  args:
    executable: /bin/bash
  connection: local
  become: true


